In [13]:
import numpy as np

In [14]:
# subtask_1
z1 = complex(3, +4)
z2 = complex(2, -2)
print("Z1+Z2 = ", z1 + z2)
print("Z1.Z2 = ", z1 * z2)
print("Z1* = ", z1.conjugate())
print("|Z1| = ", abs(z1))

Z1+Z2 =  (5+2j)
Z1.Z2 =  (14+2j)
Z1* =  (3-4j)
|Z1| =  5.0


In [15]:
# subtask_2
identity = np.identity(2)
i = np.array([[0, -1], [1, 0]])
z1 = np.array(3 * identity + 4 * i)
z2 = np.array(2 * identity - 2 * i)
print("Z1+Z2:")
print(z1 + z2, end='\n\n')
print("Z1*Z2:")
print(z1 @ z2, end='\n\n')
print("Transpose(Z1):")
print(z1.transpose(), end='\n\n')
print("Sqrt(Det(Z1)):")
print(np.sqrt(np.linalg.det(z1)), end='\n\n')

Z1+Z2:
[[ 5. -2.]
 [ 2.  5.]]

Z1*Z2:
[[14. -2.]
 [ 2. 14.]]

Transpose(Z1):
[[ 3.  4.]
 [-4.  3.]]

Sqrt(Det(Z1)):
5.000000000000001



In [16]:
print("Z1:")
print(z1, end='\n\n')
print("Z2:")
print(z2)

Z1:
[[ 3. -4.]
 [ 4.  3.]]

Z2:
[[ 2.  2.]
 [-2.  2.]]


We observe that we can represent a complex number a+bi as matrix $$\begin{bmatrix} a & -b \\ b & a \end{bmatrix}$$ and then:
- addition of complex numbers corresponds to their matrix addition
- multiplication of complex numbers corresponds to their matrix multiplication
- complex conjugate of a complex number corresponds to transpose of its matrix
- absolute value of a complex number corresponds to square root of the determinant of its matrix

In [17]:
# Bonus-1
identity = np.identity(4)
i = np.array([[0, -1, 0, 0], [1, 0, 0, 0], [0, 0, 0, -1], [0, 0, 1, 0]])
j = np.array([[0, 0, -1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, -1, 0, 0]])
k = np.array([[0, 0, 0, -1], [0, 0, -1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
print("i*j*k:")
print(i @ j @ k)

i*j*k:
[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]


In [18]:
# Bonus-2
identity = np.identity(2)
i = np.array([[complex(0, 1), 0], [0, complex(0, -1)]])
j = np.array([[0, 1], [-1, 0]])
k = np.array([[0, complex(0, 1)], [complex(0, 1), 0]])
print("i*j*k:")
print(i @ j @ k)



i*j*k:
[[-1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]
